### ISSUE TITLE
Installing via WordPress packagist not working

### ISSUE THREAD

**Issue by timiwahalahti** [wp-media/imagify-plugin#116]
For some reason, installing this plugin with composer from WordPress Packagist (https://wpackagist.org/) did broke last Saturday. In wpackagist, the plugin seems to be inactive.

Message from composer is following

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package wpackagist-plugin/imagify could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

This is kinda major, because running `composer update` brokes when Imagify is required.

**Comment by ataylorme** [comment]
I'm seeing the same issue and can't install from GitHub since this repository isn't the full build artifact and has some components needed, like `"type": "wordpress-plugin"` missing from `composer.json`.

Any chance of getting this active again on WPackagist?

**Comment by jbma** [comment]
Thank's for reporting, we are going to have a look.
@Screenfeed any idea about it?

**Comment by Screenfeed** [comment]
Probably due to our "problem" last weekend.
Better ask WP Packagist, it's not on our side since the plugin is available on the repository again.

@ataylorme You mean we should add `"type": "wordpress-plugin"` to our `composer.json`? Anything else we should add?

**Comment by ataylorme** [comment]
> You mean we should add `"type": "wordpress-plugin"` to our `composer.json`? 

Yes, [the `type` field](https://getcomposer.org/doc/04-schema.md#type) allows other items to change logic based on the type. In my case using `composer/installers` to install anything with `"type": "wordpress-plugin"` to `wp-content/plugins`, rather than `vendor`.

`name` and `description` are also required so you would need to add `description` as well.

This will allow us to install via `{"type":"vcs", "url":"https://github.com/wp-media/imagify-plugin"},` rather than WPackagist.

The issue remains though Composer would essentially clone this repo which is just the source, not the fully built plugin so I think getting WPackagist to get the plugin back to active is the better route.

**Comment by Screenfeed** [comment]
OK, thanks for the tip, I'll add these fields when I come back from holidays ;)

**Comment by Screenfeed** [comment]
Missing fields have been added.
But be aware that the field "name" has changed, it's `wp-media/imagify-plugin` now (instead of `wpmedia/imagify-plugin`).
