### ISSUE TITLE
Allow filtering default options

### ISSUE THREAD

**Issue by ronilaukkarinen** [wp-media/imagify-plugin#220]
Hello, we'd like to have Normal as default compression level, Agressive creates too low quality images. Is this possible via filter or hook? Thanks!

**Comment by Screenfeed** [comment]
Hi,

Sorry for the answer, we don't get notified of new tickets (they are not meant for support).
In the current version there is no hook for that, but will be in the next release (1.7). [This is where the default settings are set](https://github.com/wp-media/imagify-plugin/blob/master/inc/admin/upgrader.php#L45), you can probably unhook things or hook earlier. Note that it work anymore in 1.7 because lots of things will change.

Greg

**Comment by ronilaukkarinen** [comment]
Well, this was not support but more of a feature request :) when will 1.7 be out? just making sure I don't make the effort for our sites now if it's going to be soon. Thanks!

**Comment by Screenfeed** [comment]
I have no ETA yet, but development has ended, we're performing code reviews and tests. I can poke you when I have an approximate date.
The filter will be ['imagify_reset_option_values'](https://github.com/wp-media/imagify-plugin/blob/feature/custom-folders-part-20/inc/classes/class-imagify-abstract-options.php#L464).

**Comment by Screenfeed** [comment]
Maybe for next week.

**Comment by Screenfeed** [comment]
Added in 1.7.

**Comment by timiwahalahti** [comment]
Hi @Screenfeed! Looks like the filter `imagify_reset_option_values` you mentioned does not exist and neither there are any way to filter/change the options. I think supporting it would be fairly easy, since [API KEY can already be populated](https://github.com/wp-media/imagify-plugin/blob/master/inc/classes/class-imagify-options.php#L82) from server.

Could you please introduce a filter to achieve this, thanks!

**Comment by Screenfeed** [comment]
@timiwahalahti [Here](https://github.com/wp-media/imagify-plugin/blob/master/inc/classes/class-imagify-abstract-options.php#L464) it is.
