### ISSUE TITLE
Error [Table 'xxx.yy_imagify_folders' doesn't exist]

### ISSUE THREAD

**Issue by vralle** [wp-media/imagify-plugin#400]
Hi!
After updating the plugin - first viewing the admin console:
`WordPress: [Table 'xxx.yy_imagify_folders' doesn't exist]
SELECT * FROM yy_imagify_folders WHERE path IN ( '{{PLUGINS}}/ewww-image-optimizer/' ) LIMIT 1;`
further there is no error here (cache?)

Similar error is already in a different place - in the plugin settings screen, above section CUSTOM FOLDERS:
`[Table 'xxx.yy_imagify_folders' doesn't exist]
SELECT path FROM yy_imagify_folders WHERE active = 1;`

WP 5.2.2
PHP 7.3x64
Folders for optimization no set.

**Comment by Screenfeed** [comment]
Hi,

This is really strange.
Each time a page is loaded in the admin area, a test is done to verify if our tables are ready to be used, and if not, they are created. Then, upon failure, a "not ready" flag is raised. Later in the code, this flag is checked before using the tables.
It feels like the tables are not created, but tests say otherwise all along.

Could you [contact our support team](https://imagify.io/support/) so we can take a closer look?

Thanks.

**Comment by piotrbak** [comment]
Since we didn't have any follow-up and no other tickets about this, I'm going to close.
