### ISSUE TITLE
Wrong coupon displayed

### ISSUE THREAD

**Issue by Agathemed** [wp-media/imagify-plugin#511]
![Capture d’écran 2020-08-19à 15 41 31](https://user-images.githubusercontent.com/48359715/91700317-fefe4880-eb75-11ea-97f1-233b6233e65c.jpg)

The IMAGIFY20 coupon has been deactivated a while ago, users can have the new coupon automatically applied if they follow the benefits page through their Imagify account - but one of our users reported seeing this still the old coupon in the French version of the Imagify dashboard, at least.

**Comment by markonikolic985** [comment]
It looks like it is still present in [notice-wp-rocket.php](https://github.com/wp-media/imagify-plugin/blob/e914395a5b582c7b4e1798eee7bd08d088e67d1b/views/notice-wp-rocket.php) file.

**To reproduce**

- Install Imagify and make sure there is no WP Rocket active on the site.
- Go to Media > Bulk optimization
- At the top, you will see this banner:
<img width="1403" alt="Screen Shot 2020-09-02 at 10 13 59 AM" src="https://user-images.githubusercontent.com/7384779/91957302-1f5d0d00-ed06-11ea-9c0b-c3b0a16a1d58.png">

- it is present both for English and French versions

**To resolve**

Since "Get WP Rocket Now button/link works as expected (20% is applied automatically to visitor), simple change of wording and removing the coupon info should do the trick.

**Comment by mostafa-hisham** [comment]
### Scope a solution ✅ 
In `imagify/views/notice-wp-rocket.php`, 

1. remove the $coupon_code variable
https://github.com/wp-media/imagify-plugin/blob/3ae8d34d03b389d4f682db70dae8f338ff8bd07e/views/notice-wp-rocket.php#L5

2. edit string in printf text and remove the coupon part in `imagify-rkt-msg` <p>
https://github.com/wp-media/imagify-plugin/blob/3ae8d34d03b389d4f682db70dae8f338ff8bd07e/views/notice-wp-rocket.php#L14-L24

3. remove `imagify-rkt-coupon`<p>
https://github.com/wp-media/imagify-plugin/blob/3ae8d34d03b389d4f682db70dae8f338ff8bd07e/views/notice-wp-rocket.php#L25-L27




### Estimate the effort ✅
effort `[XS]`
