### ISSUE TITLE
WebP is not resized to defined size

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#521]
When using image resizing in Imagify, original image is resized to defined value, but WebP stays in original size (width/height).

**To Reproduce**

1. Go to Imagify Settings and make sure Resizing and WebP creation options are active
2. Add new Media (or optimize existing) - make sure it is larger in width (so it get resized)
3. Check original image and WebP dimensions. WebP will not be resized.

**Expected behavior**

WebP should be resized as same as the original format image.

**Screenshots**

<img width="1414" alt="Screen Shot 2020-10-09 at 11 16 25 AM" src="https://user-images.githubusercontent.com/7384779/95565982-3d164400-0a21-11eb-9171-6e2deb3f18b4.png">

**Comment by joejoe04** [comment]
I have an update on this, as I believe there is a new issue that's been brought to our attention that seems like it is closely related.

This user is on the free Starter plan and noticed that in cases where an original image is larger than 2MB in file size, the WebP version of the -scaled image is not being created even though the -scaled JPG/PNG version is optimized:

I was able to recreate this and can see the original file size of the -scaled.jpg image:

![image](https://user-images.githubusercontent.com/45705494/159997166-1cb8a65d-2024-4bc2-8e9e-a52bd5d84122.png)    

Is different than it is after optimization:

![image](https://user-images.githubusercontent.com/45705494/159997206-6272096e-a654-4a50-8dcd-749bb294abed.png)

So I think that when it comes to the -scaled.jpg.webp version, Imagify is using the original to both test whether it is under the 2MB threshold for free accounts and also when it's created (since the dimensions end up being the same as the original image).

https://secure.helpscout.net/conversation/1816476418/331742

**Comment by tictag** [comment]
Further to @joejoe04 comments above (_I am the user he mentions_), here are my own test results:

![2022-03-24_19-58-41](https://user-images.githubusercontent.com/12136834/160000092-14399228-4a5e-450f-96e4-da23c0376ddd.png)

In this case, both '_Resize [to 1024px]_' and '_Create WebP_' options are enabled on the Starter Plan.

Note that the scaled images (_all 1024x575px and approximately the same file size e.g. ~150KB_) are not actually being used for WebP conversion, instead the original images are used. The scaled images are tiny, and well under the 2MB max file size for the Starter Plan, but they all fail the WebP conversion with the same error. Note the file sizes mentioned in the error - these appear to correspond to the file sizes of the original images (red highlight).

The expected results are:

 - Scale / Optimise the image
 - Check if the scaled image is > 2MB
   - If so, die with error '2MB Starter Plan cap breached' (or similar)
   - If not, convert scaled image to WebP
 - Check if WebP image file size > scaled image file size
   - If so, ask user to accept or warn user

On resize, the original image should be of no consequence to WebP conversion - this file is now just a backup.

**Comment by tommy83** [comment]
Plugin with 600,000+ active installs waiting 2 years for a solution also in paid version?

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
I was able to reproduce the issue. The original image is resized, but the WebP image isn't.

### Identify the root cause ✅ 
The root cause is in the maybe_resize() method of the Process class. What happens is the following:
- The original image is resized
- The new dimensions are stored for the original image
- When doing the WebP conversion, the method is checking the dimensions of the resized image instead of the original one, so it considers there is no resize needed
- The WebP file is created from the original image dimensions

### Scope a solution ✅ 
A working solution is to check the dimensions using the file dimensions themselves instead of the dimensions stored in the database for the image.

### Estimate the effort ✅
effort `[XS]`
