### ISSUE TITLE
CSS conflict with Imagify

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#542]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Imagify is present, there's a CSS conflict with the `Clear Cache` button in the dashboard.

**To Reproduce**
1. Enable WP Rocket
2. Enable Imagify
3. Go to the Imagify dashboard

**Expected behavior**
WP Rocket's button shouldn't be styled in Imagify way

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/102902599-22bc0600-4467-11eb-9713-6d7e5df49c62.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
**Reproduced** ✅ 

**Root cause:**
CSS for the imagify settings page targets `.imagify-settings .button`. Thus, all buttons on the page get the imagify button styles applied.

**Scope Solution:**
Changing the CSS in `assets/css/admin.css` (currently on L:282) to exclude buttons with the `wp-core-ui` class will remove imagify styles from the core buttons. The following modified CSS works locally:
`.imagify-settings .button:not(.wp-core-ui)`

The `grunt css` task needs to be run after the update to recompile the minified version of the CSS for production.

**Estimate Effort:**
[XS]
