### ISSUE TITLE
There are still mentions about One Time plans on the pop-up message regarding "out of quota" 

### ISSUE THREAD

**Issue by ionikol** [wp-media/imagify-plugin#543]
![Screenshot 2021-01-18 152621](https://user-images.githubusercontent.com/59447333/105184278-d7654800-5b37-11eb-9e2c-590ba82dedd8.png)

https://github.com/wp-media/imagify-plugin/blob/dd798ddee4f00a774044f817e3bfa548a9dd774d/views/part-bulk-optimization-overquota-alert.php#L24

**Comment by iCaspar** [comment]
**Reproduced:** ✅ 

**Root Cause:**
HTML for this view includes reference to one-time plans.

**Scope Solution:**
Revise the view HTML around in `views/part-bulk-optimization-overquota-alert.php` to remove the one-time plan reference. Since that leaves only one item, remove all the list HTML and reword the section to simply:  
"To continue optimizing your images, you can **upgrade your subscription**."

**Estimate Effort:**
[XS]
