### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by remyperona** [wp-media/imagify-plugin#559]
There is 2 aspects to look into related to the PHP 8 compatibility for Imagify:

#### Automated tests
The plugin is currently tested with PHP 5.6 to 7.4.

We should add PHP 8 to our test matrix, the same way we did for WP Rocket.

It will require to update the `wp-media/phpunit` package to version `2.0`, and most likely update our test cases to work with it.

#### Manual testing
The QA team can test the plugin on a PHP 8 installation to see if we can find known issues by using the plugin from a user point of view.

**Comment by iCaspar** [comment]
## Grooming Notes:

### Reproduce Issue: 
- [X] Running phpcs against `--standard=vendor/phpcompatibility/php-compatibility/PHPCompatibility --runtime-set testVersion 8.0` throws no warnings or errors.
- [x] @wp-media/qa to run smoke/regression tests on a php8 install -- please note any issues found below.

### Root Cause:
- TBD (if any)

### Scope Resolution(s)
- [ ] PHP8 added to CI matrix
- [ ] `wp-media/phpunit` package updated to v2
- [ ] Any failing tests resulting from phpunit update resolved
- [x] Any issues found by QA smoke resolved

### Estimate Effort
- [S - M] (depending on QA preliminary results)

**Comment by piotrbak** [comment]
Tried all options on PHP8 and everything worked + no entries in the log

**Comment by remyperona** [comment]
@iCaspar I set the task to [S], and moved it back to to-do, to make the changes in the CI, composer configuration and test cases. This can be done at anytime during the sprint, as it's not a blocker for the release 👍🏼

**Comment by piotrbak** [comment]
To test this, I run the composer install command and made smoke tests on PHP8. That should be enough.
