### ISSUE TITLE
Add setting to optimize only Used Images across the site

### ISSUE THREAD

**Issue by gevcen** [wp-media/imagify-plugin#596]
**Is your feature request related to a problem? Please describe.**
When performing the mass optimization, this feature optimizes all images of the database.

**Describe the solution you'd like**
There is no real need to optimize ALL images of the database, especially that a lot of them may not be used anymore, therefore not relevant to use quota to optimize them.

**Describe alternatives you've considered**
Please provide us a setting that would allow us to only optimize USED images across the site, and bypass the images that are not used in the site since it's irrelevant to optimize them.

**Additional context**
N/A

**Comment by GeekPress** [comment]
Hi @gevcen 

Sorry for the late response.

I totally understand the need, but I'm afraid it's not something we could easily do.

Why?
Because there is no way to quickly filter and find the images you would like to exclude. All images are stored in the `wp-upload` folder or in a monthly folder.

Also, we can't rely on the condition if the image is attached to a post. An image not attached to any post can be used anywhere else.

PS: I'm closing the issue now, but feel free to comment to continue the discussion.
