### ISSUE TITLE
Media Library Filter does not work in combination with file type

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#670]
When on Media Library (List VIew), there is possibility to filter files by type, date and optimization status (this one is coming from Imagify).

However, if you choose specific file type (images, documents...) and specific optimization status, the filter will not work - all file types are still displayed.

This works with date filter, but not with file type filter.

**To Reproduce**
1. Go to Media Library
2. Choose List View
3. Choose Documents or Images from the first filter
4. Choose Optimized/Unoptimized/Errors from the third filter
5. Still all file types will show up
6. If you change only one filter, it will work

**Screenshots**
<img width="1263" alt="Screenshot 2022-05-24 at 13 46 54" src="https://user-images.githubusercontent.com/7384779/170028939-6272b29e-30ba-4283-89e7-a5dec0ebd137.png">

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I was able to reproduce the issue.
## Identify the root cause
The root cause is due to the fact we are overriding `post_mime_type` on the query even when it is already set.

## Scope a solution
To fix this issue we need to replace that code:
```php
	$vars['post_mime_type'] = imagify_get_mime_types();
```

with that one :
```php
    if(! key_exists('post_mime_type', $vars)) {
        $vars['post_mime_type'] = imagify_get_mime_types();
    }
```

[On line 126](https://github.com/wp-media/imagify-plugin/blob/develop/inc/admin/upload.php#L126) from `inc/admin/upload.php`.
## Estimate the effort
Effort `XS`
