### ISSUE TITLE
Improve information related to out of quota on the bulk

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#714]
**Is your feature request related to a problem? Please describe.**
Once the bulk optimization is launched and all the quota is consumed, we don't directly display the information about the quota. Instead it looks like the bulk is continuing.

That's for example how this is displayed on the bulk (the user has consumed all his quota) : 
![image](https://user-images.githubusercontent.com/2565525/222163002-35833ea8-c56e-4a98-901b-c43f1be05b05.png)

**Describe the solution you'd like**
Instead we should directly use the popin we were using before to warn the user about the quota and provide him a solution.

**Comment by CrochetFeve0251** [comment]
@jbma to confirm we need to show the exact same popup he got at 20% storage remaining again even if the customer already clicked on it by the past to dismiss it?
Or we need a new one looking the same way.

**Comment by jbma** [comment]
In the previous version when the quota was 0, when we tried to launch the bulk optimization or when running (we had to stay on the same page, wasn't async) a popin was displayed when launching the bulk or when it was running.

I guess here the best solution would be to display the popin each time we go the bulk when the quota is 0

**Comment by CrochetFeve0251** [comment]
## Scope a solution
To activate the popup when the quota is over we need to modify two classes to add the following logic:
- [`classes/Notices/Notices.php`](https://github.com/wp-media/imagify-plugin/blob/develop/classes/Notices/Notices.php) where we will have to modify the method [`display_almost_over_quota`](https://github.com/wp-media/imagify-plugin/blob/46f9df25cc18fe7a8609d1a94bec039e169282da/classes/Notices/Notices.php#L449):
First we will need to move  [`$user` instantiation](https://github.com/wp-media/imagify-plugin/blob/46f9df25cc18fe7a8609d1a94bec039e169282da/classes/Notices/Notices.php#L470) over the [`self::notice_is_dismissed( 'almost-over-quota' )` condition](https://github.com/wp-media/imagify-plugin/blob/46f9df25cc18fe7a8609d1a94bec039e169282da/classes/Notices/Notices.php#L466) and add a check if the quota different from zero on that condition:
```php
		$user = new \Imagify_User();

		if ( self::notice_is_dismissed( 'almost-over-quota' ) && $user->get_percent_unconsumed_quota() !== 0 ) {
			return $display;
		}
```
- [`inc/classes/class-imagify-user.php`](https://github.com/wp-media/imagify-plugin/blob/develop/inc/classes/class-imagify-user.php) where we will have to modify the method [`get_percent_consumed_quota`](https://github.com/wp-media/imagify-plugin/blob/46f9df25cc18fe7a8609d1a94bec039e169282da/inc/classes/class-imagify-user.php#L154):
We will have to a new condition checking for 100% on [the 80% condition](https://github.com/wp-media/imagify-plugin/blob/46f9df25cc18fe7a8609d1a94bec039e169282da/inc/classes/class-imagify-user.php#L199) launching `imagify_not_almost_over_quota_anymore` action:
```php
if ( ( (float) $previous_percent >= 80.0 && $percent < 80 )  || $percent === 100 ) {
```
## Estimate the effort
Effort `XS`

PS:
@Tabrisrp while doing that I got no popup displaying due to no [results](https://github.com/wp-media/imagify-plugin/blob/46f9df25cc18fe7a8609d1a94bec039e169282da/classes/Notices/Notices.php#L253) found in `renew_almost_over_quota_notice` method, could you confirm that value would be filled if we reach 80% usage?
