### ISSUE TITLE
PHP Deprecated notice when upgraded to PHP 8.2

### ISSUE THREAD

**Issue by ionikol** [wp-media/imagify-plugin#723]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The user on this [ticket](https://secure.helpscout.net/conversation/2223555674/416197?folderId=676697) received the following PHP Deprecated notice when upgraded to PHP 8.2

Deprecated: Creation of dynamic property Imagify\MediaOptimization::$query_url is deprecated in wp-content/plugins/imagify/inc/classes/class-imagify-abstract-background-process.php on line 38

**Expected behavior**
No deprecated notice

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Identify the root cause
The root cause is due to an error done in the `Imagify_Abstract_Background_Process` class.

The `query_url` property is not definted.

## Scope a solution
Define the `query_url` property inside the[ `Imagify_Abstract_Background_Process`](https://github.com/wp-media/imagify-plugin/blob/devealop/inc/classes/class-imagify-abstract-background-process.php) class:
## Estimate the effort
Effort `XS`
