### ISSUE TITLE
AVIF images arenot automatically generated for existing images after enabling the option

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#796]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Avif commit: https://github.com/wp-media/imagify-plugin/commit/b396de27cda71d9b16e311a0f55f482bebf13380
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling AVIF, it isnot automatically generate AVIF for existing images in the media library

**To Reproduce**
1. Fresh activation of imagify
2. Upload a couple of images
3. Enable create AVIF option and save 
4. Check FTP for images in 2 => AVIF not generated

**Expected behavior**
AVIF version is generated and quota is affected 

**Additional context**
- related discussion https://wp-media.slack.com/archives/C069W48E47N/p1706878004622759?thread_ts=1706877044.964199&cid=C069W48E47N

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Miraeld** [comment]
Umm, from my tests, here are some complementary informations:

- If we have the options `Auto-Optimize images on upload` but `AVIF` is disabled, when we upload images it gets optimized on upload, and get this status in the DB (`wp_postmeta`):

| meta_key | meta_value |
|--|--|
| _imagify_status | already_optimized |

Because of this, when we enable `AVIF` and save, it gets to this [line](https://github.com/wp-media/imagify-plugin/blob/de6dc98d592a607b52baa89918d3d3c6b7ee8460/classes/Bulk/Bulk.php#L179) where we get the unoptimized `media_ids`. However, as the status says `already_optimized` it won't return these images IDs.


- If we disable the options `Auto-Optimize images on upload`, upload images, and we enable `AVIF` and save, it will generate `.avif` files. 


So the problems lies in the fact that `Auto-Optimize images on upload` set the status at `already_optimized` so images aren't getting picked up by the bulk optimization when we save with `AVIF` enabled.

**Comment by piotrbak** [comment]
@Miraeld Could you check how [this button](https://github.com/wp-media/imagify-plugin/blob/431a4ff2ca8d9668a840386c34365854726ec0b4/views/part-settings-webp.php#L142) works in the current version? The behaviour should be very similar

**Comment by Miraeld** [comment]
I've compared a bit with `develop` branch. 
From what I am seeing, 

* When `Auto-optimized` is disabled, and we upload an image, we don't get the status `already_optimized` in the DB. 
It means we have a problem here with the `AVIF` branch. 



@piotrbak I've tried to check the button, but it is also not working on `avif` branch, and I was trying to debug it on `develop` to see how it works, and why we could get an error, but once i clicked it one time it disappeared forever, even when I upload new images which aren't optimized. So not sure yet, I'm trying to figure out the differences between `develop` and `avif` on the upload part.

**Comment by Mai-Saad** [comment]
If we have single large image in media library then enabled AVIF, the AVIF won't be generated in background (tested local using attached image) @Miraeld can you please check if it's working for this image? (note: bulk notice wasnot displayed in this case)
![mountain](https://github.com/wp-media/imagify-plugin/assets/76941962/6c6713a8-1ccc-410c-a81d-4346fb64da36)

**Comment by Miraeld** [comment]
@Mai-Saad , I've created this PR https://github.com/wp-media/imagify-plugin/pull/811 to take care of this last feedback.
