### ISSUE TITLE
Can sweetalert wrapper be added on the fly?

### ISSUE THREAD

**Issue by jondcampbell** [wp-media/imagify-plugin#84]
Right now the div.swal2-container gets added to the page by Imagify on page load in the admin areas but it would be great if that container got dynamically added to the <body> when it's needed instead of on page load.
From what I can tell that's how the default sweetalert2 works: https://limonte.github.io/sweetalert2/

That div container gets added when the alert opens and removed when the alert hides.

This way other scripts using sweetalerts don't have to worry about your wrapper div being there on the page and having their css applied to your div.

Hope that makes some sense.

**Comment by Screenfeed** [comment]
Hello.
That doesn't seem possible with the version we use, SweetAlert initiates itself on page load: https://github.com/wp-media/imagify-plugin/blob/master/assets/js/sweetalert2.js#L1325
I'm not sure but I think it's possible with a more recent version.
I can't say when we'll update it though, because all our code needs to be tested (and maybe updated) after that. But a ticket is open for that.

**Comment by Screenfeed** [comment]
Closed by 5a6a6a2.

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by Screenfeed** [comment]
Thank you @limonte, I updated the message.
