### ISSUE TITLE
Handle the case if  new thumbnails are added for optimized images

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#90]
The only solution for now to optimize the new thumbnails is to restore and re-optimize the image.

**Comment by Screenfeed** [comment]
This is something that can't be achieved with our current data structure.
But this is something to keep in mind for a future new data structure.

**Comment by Screenfeed** [comment]
Actually, I'm thinking on a way to do it with the current data structure. But I don't think it will be possible to bulk it: I can't think of a way to SQL select attachments with non-optimized images

**Comment by Screenfeed** [comment]
POC:

![capture d ecran 2017-08-07 17 26 25](https://user-images.githubusercontent.com/1878479/29033592-d36eff6e-7b95-11e7-8b7a-14d9665f702d.png)

Cons:
- It's impossible to build a SQL query that would fetch the attachments where one or more thumbnails are missing, it needs calculation with php. That means we won't be able to have a "global bulk" like our bulk optimization page, unless we fetch ALL attachment IDs and test them one after the other, which is impossible for huge libraries.
- When we switch theme, the "basic" sizes dimensions change: this feature doesn't detect that, that's not what it is about here.

Pros:
- You see "Optimize 1 missing thumbnail", that means it can be "Optimize 3 missing thumbnails" ;)
- It counts thumbnails that are missing AND needed. For instance, an image (full size) 50px × 60px, and a thumbnail size 1200px × 800px: in that case, WP would not create the thumbnail because it's not needed (it's too big), so this feature would not label it as missing.
